# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv", comment="#", dtype="str")

# Generate useful variables
SAMPLES = samples["sample"].drop_duplicates().values.tolist()

# Import subworkflows
include: "rules/common.smk"
include: "rules/folders.smk"
include: "rules/reads.smk"
include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/map_human.smk"
#include: "rules/map_chicken.smk"
#include: "rules/map_mag_catalogue.smk"

rule all:
    input:
        rules.reads_fastqc_all.input,
        rules.fastp_all.input,
        rules.map_human_all.input
