# Configuration file for the features, aka, references
---
reference:
  human: resources/reference/human_22_sub.fa.gz
  chicken: resources/reference/chicken_39_sub.fa.gz

mag_catalogues:
  mag1: resources/reference/mags_sub.fa.gz
  mag2: resources/reference/mags_sub.fa.gz

kraken2_dbs:
  mock_db1: resources/kraken2_mock
  mock_db2: resources/kraken2_mock
